import type { Metadata } from "next";
import { Geist, Geist_Mono, Jaro } from "next/font/google";
import ReduxProvider from "./redux/providerLayout";
import "./globals.css";

import { ToastContainer } from "react-toastify";
import LoggedInLayout from "./loggedIn/LoggedInLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jaro = Jaro({
  variable: "--font-jaro",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jaro.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
        id="root"
      >
        <ReduxProvider>
          <LoggedInLayout>{children}</LoggedInLayout>
          <ToastContainer />
        </ReduxProvider>
      </body>
    </html>
  );
}
